security:
    providers:
        webservice:
            id: App\Security\User\WebserviceUserProvider
    encoders:
        App\Entity\User: bcrypt
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login
                success_handler: App\Security\Http\Authentication\AuthenticationHandler
                failure_handler: App\Security\Http\Authentication\AuthenticationHandler

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
