<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\UserRESTController:postAction' => function () {
    return ${($_ = isset($this->services['service_locator.nbiood2']) ? $this->services['service_locator.nbiood2'] : $this->load('getServiceLocator_Nbiood2Service.php')) && false ?: '_'};
}, 'App\\Controller\\UserRESTController:putAction' => function () {
    return ${($_ = isset($this->services['service_locator.xyq9u_n']) ? $this->services['service_locator.xyq9u_n'] : $this->load('getServiceLocator_Xyq9uNService.php')) && false ?: '_'};
}, 'App\\Controller\\UserRESTController::postAction' => function () {
    return ${($_ = isset($this->services['service_locator.nbiood2']) ? $this->services['service_locator.nbiood2'] : $this->load('getServiceLocator_Nbiood2Service.php')) && false ?: '_'};
}, 'App\\Controller\\UserRESTController::putAction' => function () {
    return ${($_ = isset($this->services['service_locator.xyq9u_n']) ? $this->services['service_locator.xyq9u_n'] : $this->load('getServiceLocator_Xyq9uNService.php')) && false ?: '_'};
})));
