<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBywdaec\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBywdaec/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBywdaec.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBywdaec\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBywdaec\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Bywdaec',
    'container.build_id' => 'cede04fd',
    'container.build_time' => 1533069193,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBywdaec');
